const db = window.supabase.createClient(window.APP_CONFIG.url, window.APP_CONFIG.key);
const labels={status:{pending:"待处理",processing:"处理中",completed:"已完成",closed:"已关闭"},priority:{low:"低",medium:"中",high:"高"},action:{create:"创建",inquiry:"询问",reply:"回复",status_change:"状态变更",note:"备注"}};
let allTickets=[];
async function sendFeishu(ticket, textLine) {
  if (!window.APP_CONFIG.adminWebhook) return;
  const text=`【工单更新】\n工单ID: ${ticket.id}\n工单标题: ${ticket.info.title}\n问题描述: ${ticket.info.description}\n提交人姓名: ${ticket.name||"-"}\n${textLine}`;
  try { await fetch(window.APP_CONFIG.adminWebhook,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({msg_type:"text",content:{text}})}); } catch {}
}
const esc=(value)=>String(value??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const unpack=(row)=>{let info={title:row.title||"未命名工单",description:row.description||"",phone:row.phone||"",email:row.email||"",legacy_id:null,tracks:[]};try{const parsed=JSON.parse(row.description);if(parsed?.version===2)info={...info,...parsed};}catch{}return{...row,info,tracks:info.tracks||[]};};
function notice(text){const box=document.querySelector("#notice");box.textContent=text;box.hidden=false;setTimeout(()=>box.hidden=true,2200);}
async function load(){const {data,error}=await db.from("tickets_type2").select("*").order("created_at",{ascending:false});if(error){document.querySelector("#ticketList").innerHTML='<div class="empty-state">工单加载失败</div>';return;}allTickets=(data||[]).map(unpack);render();}
function filtered(){const q=document.querySelector("#search").value.trim().toLowerCase(),s=document.querySelector("#statusFilter").value,p=document.querySelector("#priorityFilter").value;return allTickets.filter(t=>(!q||`${t.info.title} ${t.info.description}`.toLowerCase().includes(q))&&(s==="all"||t.status===s)&&(p==="all"||t.priority===p));}
function render(){document.querySelector("#total").textContent=allTickets.length;document.querySelector("#pending").textContent=allTickets.filter(t=>t.status==="pending").length;document.querySelector("#processing").textContent=allTickets.filter(t=>t.status==="processing").length;document.querySelector("#completed").textContent=allTickets.filter(t=>t.status==="completed").length;const rows=filtered();document.querySelector("#countLabel").textContent=`共 ${rows.length} 个工单${rows.length!==allTickets.length?"（已筛选）":""}`;document.querySelector("#ticketList").innerHTML=rows.length?rows.map(card).join(""):'<div class="empty-state">暂无符合条件的工单</div>';bind();}
function card(t){return `<article class="ticket-card" data-id="${t.id}"><div class="ticket-summary"><button class="ticket-title-button expand"><span class="priority-dot ${esc(t.priority)}"></span><span><strong>#${t.id} · ${esc(t.info.title)}</strong><small>${new Date(t.created_at).toLocaleString("zh-CN")}</small></span></button><div class="ticket-controls"><span class="priority-badge ${esc(t.priority)}">${labels.priority[t.priority]||"中"}</span><select class="status-select"><option value="pending"${t.status==="pending"?" selected":""}>待处理</option><option value="processing"${t.status==="processing"?" selected":""}>处理中</option><option value="completed"${t.status==="completed"?" selected":""}>已完成</option><option value="closed"${t.status==="closed"?" selected":""}>已关闭</option></select><button class="icon-button danger delete">删除</button></div></div><p class="ticket-description">${esc(t.info.description)}</p><div class="contact-row"><span>提交人：${esc(t.name||"—")}</span><span>电话：${esc(t.info.phone||"—")}</span><span>邮箱：${esc(t.info.email||"—")}</span></div><div class="ticket-details" hidden>${tracksHtml(t)}<form class="track-form"><select name="action"><option value="reply">回复</option><option value="inquiry">询问</option><option value="note">备注</option></select><input name="content" placeholder="输入跟踪内容..." required><button class="button primary">添加</button></form></div></article>`;}
function tracksHtml(t){return `<h3>跟踪记录（${t.tracks.length}）</h3><div class="timeline">${t.tracks.length?t.tracks.map(x=>`<div class="track-item"><span class="timeline-dot"></span><div><strong>${labels.action[x.action]||"备注"}</strong><p>${esc(x.content)}</p><small>${esc(x.operator||"—")} · ${new Date(x.created_at).toLocaleString("zh-CN")}</small></div></div>`).join(""):'<p class="muted">暂无跟踪记录</p>'}</div>`;}
function bind(){document.querySelectorAll(".ticket-card").forEach(card=>{const id=Number(card.dataset.id),ticket=allTickets.find(t=>t.id===id);card.querySelector(".expand").onclick=()=>{const d=card.querySelector(".ticket-details");d.hidden=!d.hidden;};card.querySelector(".status-select").onchange=async e=>{const old=ticket.status,next=e.target.value;const tracks=[...ticket.tracks,{action:"status_change",content:`状态由“${labels.status[old]}”变更为“${labels.status[next]}”`,operator:"管理员",created_at:new Date().toISOString()}];const description=JSON.stringify({...ticket.info,tracks});const {error}=await db.from("tickets_type2").update({status:next,description}).eq("id",id);if(error)notice("更新失败");else{void sendFeishu(ticket,`状态变更: ${labels.status[old]} → ${labels.status[next]}`);notice("状态已更新");await load();}};card.querySelector(".delete").onclick=async()=>{if(!confirm(`确定删除工单 #${id} 吗？此操作无法撤销。`))return;const {error}=await db.from("tickets_type2").delete().eq("id",id);if(error)notice("删除失败");else{notice("工单已删除");await load();}};card.querySelector(".track-form").onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),content=String(fd.get("content")).trim(),tracks=[...ticket.tracks,{action:fd.get("action"),content,operator:"管理员",created_at:new Date().toISOString()}];const description=JSON.stringify({...ticket.info,tracks});const {error}=await db.from("tickets_type2").update({description}).eq("id",id);if(error)notice("添加失败");else{void sendFeishu(ticket,`新的处理内容: ${content}`);notice("跟踪记录已添加");await load();}};});}
["search","statusFilter","priorityFilter"].forEach(id=>document.querySelector(`#${id}`).addEventListener(id==="search"?"input":"change",render));
document.querySelector("#clearFilters").onclick=()=>{document.querySelector("#search").value="";document.querySelector("#statusFilter").value="all";document.querySelector("#priorityFilter").value="all";render();};
load();
